POST http://localhost:8000/api/customer/signup
Content-Type: application/json

{
    "username": "tonystark",
    "email": "tonystark@gmail.com",
    "password": "Tony@123",
    "confirmPwd": "Tony@123",
    "isMember": false
}

###

POST http://localhost:8000/api/customer/signin
Content-Type: application/json

{
    "email": "tonystark@gmail.com",
    "password": "Tony@123"
}

###

GET http://localhost:8000/api/customer/info
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJUb255IiwiZW1haWwiOiJ0b255c3QyM0BnbWFpbC5jb20iLCJpc01lbWJlciI6ZmFsc2UsInBhc3N3b3JkIjoiJDJiJDEwJGhIWEdQWWM1MWhRekthNVlwSWRBbE9YRi52eWwxMHJ3ZnFnMGJoQ2EzS1NOT05zWDQuTlJ5IiwiY3JlYXRlZEF0IjoiMjAyMy0wNi0yOVQwNjo1NTozOC4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNi0yOVQwNjo1NTozOC4wMDBaIiwiaWF0IjoxNjg4MDIxNzQ1fQ.Iim1K089REwsJh6gET796Rcj1B0TOkzjMK4nu2kt6Fc 

###
POST http://localhost:8000/api/customer/add-friend
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJBYmhpc2hlayIsImVtYWlsIjoiYWthbHlhbmU5ODBAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcDNCTFNCYlJaUGlmaEk0V2V5ZGg3dVBjVzZKMHp2alVmczRDOVJWaXJTb2lYQkZFZno0anEiLCJpc01lbWJlciI6ZmFsc2UsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjlUMDY6NTk6MjguNDkzWiIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjlUMDY6NTk6MjguNDkzWiIsImlhdCI6MTY4ODAyMTk2OH0.VtzG2qXRo2jf0OenBCI3asVDnQH5eQXlr8vxYV-CLBA 

{
    "friendId": 2
}
###

GET http://localhost:8000/api/customer/list-friends?status=Pending
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJBYmhpc2hlayIsImVtYWlsIjoiYWthbHlhbmU5ODBAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmIkMTAkcDNCTFNCYlJaUGlmaEk0V2V5ZGg3dVBjVzZKMHp2alVmczRDOVJWaXJTb2lYQkZFZno0anEiLCJpc01lbWJlciI6ZmFsc2UsInVwZGF0ZWRBdCI6IjIwMjMtMDYtMjlUMDY6NTk6MjguNDkzWiIsImNyZWF0ZWRBdCI6IjIwMjMtMDYtMjlUMDY6NTk6MjguNDkzWiIsImlhdCI6MTY4ODAyMTk2OH0.VtzG2qXRo2jf0OenBCI3asVDnQH5eQXlr8vxYV-CLBA 
###

POST http://localhost:8000/api/group/create-group
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywidXNlcm5hbWUiOiJqZXJyeSIsImVtYWlsIjoiamVycnlAZ21haWwuY29tIiwiaXNNZW1iZXIiOmZhbHNlLCJwYXNzd29yZCI6IiQyYiQxMCRZSWlYVUxLamV6TDU4Nzh5MnhpQ00uTXAwLnNlTGRyeTc3MzVyQ25CZVlTNndxT1h5MFU1UyIsImNyZWF0ZWRBdCI6IjIwMjMtMDctMjEgMDU6Mzc6MjQiLCJ1cGRhdGVkQXQiOiIyMDIzLTA3LTIxIDA1OjM3OjI0IiwiaWF0IjoxNjg5OTE4MzQ2fQ.3qyzVJw1Gs_iCwMo09OTR0Nx7FmmUNg-9WwuB0bJb2s

{
    "title": "My Group 2",
    "description": "This is an awesome group 2"
}
###

GET http://localhost:8000/api/group/fetch-groups
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ0b255c3RhcmsiLCJlbWFpbCI6InRvbnlzdGFya0BnbWFpbC5jb20iLCJpc01lbWJlciI6ZmFsc2UsInBhc3N3b3JkIjoiJDJiJDEwJHNvREhoL1duVXZidnZHVmVNNDBLV2VhREsyMDFWdFJFaG16cWtnOGpTcC5lMWYxVnoubEVpIiwiY3JlYXRlZEF0IjoiMjAyMy0wNy0yMVQwNTozNjoyMS4wMDBaIiwidXBkYXRlZEF0IjoiMjAyMy0wNy0yMVQwNTozNjoyMS4wMDBaIiwiaWF0IjoxNjg5OTE5MzI0fQ.NJhiyfol0xxFEbaBLlMmg11HP05iuC8QhzA3gJWy8zo
###

GET http://localhost:8000/api/group/join-group/1
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwidXNlcm5hbWUiOiJ0b255c3RhcmsiLCJlbWFpbCI6InRvbnlzdGFya0BnbWFpbC5jb20iLCJpc01lbWJlciI6ZmFsc2UsInBhc3N3b3JkIjoiJDJiJDEwJHNvREhoL1duVXZidnZHVmVNNDBLV2VhREsyMDFWdFJFaG16cWtnOGpTcC5lMWYxVnoubEVpIiwiY3JlYXRlZEF0IjoiMjAyMy0wNy0yMSAwNTozNjoyMSIsInVwZGF0ZWRBdCI6IjIwMjMtMDctMjEgMDU6MzY6MjEiLCJpYXQiOjE2ODk5MTg4MDh9.HNZnaXhDDUEEhJAUaIkoi3527LsQKpBenj4iwFOiinA


